stages:
  - build
  - test
  - deploy_stage
  - deploy_prod
  - notify


build:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | 
            base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        - >-
            /kaniko/executor
            --context "${CI_PROJECT_DIR}"
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}"
            
test:
  stage: test
  image: python:3.6.0-alpine
  script:
    - pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py

deploy_to_stage:
  stage: deploy_stage
  image: ${CI_REGISTRY}/project_dev/infra:latest
  variables:
    deploy_variable: "stage"
  before_script:
  - for VARNAME in $(env); do
      if [[ $( echo $VARNAME | egrep '^ENV_') ]]; then
          echo -e $VARNAME;
          NAME=$(echo "$VARNAME" | cut -d"=" -f1 | sed  "s/ENV_/env./");
          VAR=$(echo "$VARNAME" | cut -d"=" -f2-);
          ENVVARS="${ENVVARS} --set $NAME=$VAR";
      fi
    done
  script:
    - yc config set service-account-key $YC_TOKEN
    - yc managed-kubernetes cluster get-credentials test-cluster --external --force
    - helm upgrade --install -n ${deploy_variable} crawler ./.cicd/crawler $ENVVARS
    - sh ./.cicd/.ci-notify.sh stage_deploy✅

deploy_to_prod:
  stage: deploy_prod
  image: ${CI_REGISTRY}/project_dev/infra:latest
  variables:
    deploy_variable: "prod"
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      variables:
        deploy_variable: "prod"
  when: manual 
  before_script:
  - for VARNAME in $(env); do
      if [[ $( echo $VARNAME | egrep '^ENV_') ]]; then
          echo -e $VARNAME;
          NAME=$(echo "$VARNAME" | cut -d"=" -f1 | sed  "s/ENV_/env./");
          VAR=$(echo "$VARNAME" | cut -d"=" -f2-);
          ENVVARS="${ENVVARS} --set $NAME=$VAR";
      fi
    done
  script:
    - yc config set service-account-key $YC_TOKEN
    - yc managed-kubernetes cluster get-credentials test-cluster --external --force
    - helm upgrade --install -n ${deploy_variable} crawler ./.cicd/crawler --set image=${CI_COMMIT_SHORT_SHA} $ENVVARS
    - sh ./.cicd/.ci-notify.sh prod_deploy ✅

notify_error:
  stage: notify
  script:
  - sh ./.cicd/.ci-notify.sh ❌
  when: on_failure
