apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  selector:
    app: crawler
  ports:
    - protocol: TCP
      name: main
      port: 8000
      targetPort: crawler
